name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Altere para a sua branch principal se for diferente

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: # Adicionado: Permissões necessárias para o GitHub Pages
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install dependencies 
        run: npm install

      - name: Build 🏗️
        run: npm run build

      - name: Deploy to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs # A pasta que o Vite gera
          cname: example.com # Opcional: se você tiver um domínio personalizado